name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below to help us understand and reproduce the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe what happened and what you expected to happen
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Please provide detailed steps to reproduce the issue
      placeholder: |
        1. Run command '...'
        2. With configuration '...'
        3. See error
      value: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe the expected behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened, include error messages if any
    validations:
      required: true

  - type: dropdown
    id: version
    attributes:
      label: POPS CLI Version
      description: What version of POPS CLI are you using?
      options:
        - Latest (from main branch)
        - v1.0.0
        - v0.9.x
        - Other (please specify in additional context)
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - macOS
        - Linux (Ubuntu)
        - Linux (other)
        - Windows
        - Other (please specify)
    validations:
      required: true

  - type: dropdown
    id: installation
    attributes:
      label: Installation Method
      description: How did you install POPS CLI?
      options:
        - Binary download
        - Homebrew
        - npm
        - Built from source
        - Other (please specify)
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: |
        Please share relevant configuration details (remove sensitive information like tokens)
      placeholder: |
        ```toml
        [jira]
        base_url = "https://example.atlassian.net"
        project = "PROJ"
        # ... other config
        ```
      render: toml

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: |
        Please include any relevant error logs. You can get verbose logs by running:
        `DEBUG=pops:* pops [command]`
      placeholder: Paste error logs here
      render: shell

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: |
        Add any other context about the problem here. Screenshots, environment details, etc.
      placeholder: Any additional information that might help

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please verify the following before submitting
      options:
        - label: I have searched existing issues to make sure this is not a duplicate
          required: true
        - label: I have provided a clear description of the problem
          required: true
        - label: I have included steps to reproduce the issue
          required: true
        - label: I have included relevant configuration and logs
          required: true