name: Build Release Binaries

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build-binaries:
    name: Build Binaries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build
        run: bun run build

      - name: Build Binaries
        run: bun run build:binaries-all

      - name: Test Binaries
        run: |
          chmod +x dist/pops-*
          ./dist/pops-linux-x64 --version
          ./dist/pops-macos-arm64 --version

      - name: Generate Checksums
        run: |
          cd dist
          sha256sum pops-* > checksums.txt
          cat checksums.txt

      - name: Upload Binaries to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.upload_url }}
          asset_path: ./dist/pops-linux-x64
          asset_name: pops-linux-x64
          asset_content_type: application/octet-stream

      - name: Upload macOS ARM64 Binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.upload_url }}
          asset_path: ./dist/pops-macos-arm64
          asset_name: pops-macos-arm64
          asset_content_type: application/octet-stream

      - name: Upload macOS x64 Binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.upload_url }}
          asset_path: ./dist/pops-macos-x64
          asset_name: pops-macos-x64
          asset_content_type: application/octet-stream

      - name: Upload Windows Binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.upload_url }}
          asset_path: ./dist/pops-windows-x64.exe
          asset_name: pops-windows-x64.exe
          asset_content_type: application/octet-stream

      - name: Upload Install Script
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.upload_url }}
          asset_path: ./install.sh
          asset_name: install.sh
          asset_content_type: text/plain

      - name: Upload Checksums
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.upload_url }}
          asset_path: ./dist/checksums.txt
          asset_name: checksums.txt
          asset_content_type: text/plain
