name: Release Please

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    name: Release Please
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build
        run: bun run build

      - name: Run tests
        run: bun test

      - name: Release Please
        uses: googleapis/release-please-action@v4
        with:
          config-file: release-please-config.json
          token: ${{ secrets.GITHUB_TOKEN }}
          command: release

  build-binaries:
    name: Build Binaries
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build
        run: bun run build

      - name: Build Binaries
        run: bun run build:binaries-all

      - name: Test Binaries
        run: |
          chmod +x dist/pops-*
          ./dist/pops-linux-x64 --version
          ./dist/pops-macos-arm64 --version

      - name: Generate Checksums
        run: |
          cd dist
          sha256sum pops-* > checksums.txt
          cat checksums.txt

      - name: Upload Binaries to Release
        uses: actions/upload-artifact@v4
        with:
          name: release-binaries-${{ github.event.release.tag_name }}
          path: |
            dist/pops-*
            dist/checksums.txt
