name: Semantic Release

on:
  push:
    branches: [main]
  workflow_dispatch:
  # Run after CI completes successfully
  workflow_run:
    workflows: ["CI"]
    types: [completed]
    branches: [main]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    # Only run if CI workflow succeeded
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build
        run: bun run build

      - name: Run tests
        run: bun test

      - name: Semantic Release
        id: semantic-release
        run: bunx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Binaries
        if: steps.semantic-release.outputs.new-release-published == 'true'
        run: bun run build:binaries-all

      - name: Test Binaries
        if: steps.semantic-release.outputs.new-release-published == 'true'
        run: |
          chmod +x dist/pops-*
          ./dist/pops-linux --version
          ./dist/pops-macos --version

      - name: Generate Checksums
        if: steps.semantic-release.outputs.new-release-published == 'true'
        run: |
          cd dist
          sha256sum pops-* > checksums.txt
          cat checksums.txt

      - name: Upload Binaries to Release
        if: steps.semantic-release.outputs.new-release-published == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: release-binaries-${{ steps.semantic-release.outputs.new-release-version }}
          path: |
            dist/pops-*
            dist/checksums.txt
